### ISSUE TITLE
Project deployment

### ISSUE THREAD

**Issue by Ant3qqq** [microsoftgraph/msgraph-sample-office-addin#147]
Hello everyone!

Sorry if it is not a place to ask this kind of questions (if it is not, could you please tell me where to ask it?). 
Would you consider adding a deployment instruction to this toutorial? I look for tips on how to deploy the Excel Web Addin in Corporate environment. Is this tutorial suitable for this example https://learn.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure?

**Comment by jasonjoh** [comment]
Publishing and hosting is a bit out of scope for this sample. However, Office add-ins are just web apps, so the hosting is mainly just a matter of having a web server to deploy to. You could certainly deploy to Azure using the link you gave, but you could also host it on any web server.

**Comment by Ant3qqq** [comment]
Thanks!
