### ISSUE TITLE
the addin is stuck stuck on screen checking authentication

### ISSUE THREAD

**Issue by Wladefant** [microsoftgraph/msgraph-sample-office-addin#275]
![image](https://github.com/user-attachments/assets/74d076c5-8e1c-4e88-a494-6e3cac0b2d1c)

What debugging steps can I do to find the problem. Can you reproduce this error?

**Comment by jasonjoh** [comment]
No, I do not reproduce it. I would double-check all of the details on your app registration. From your screen shot, it doesn't appear that you're using this sample, or you're using an older version of it?

For debugging, you can load the add-in in the web version of Excel and use the developer tools to debug the JavaScript code.

**Comment by Wladefant** [comment]
Yes that was the newest version and I tried the updated version with the updated packages too. Why do you say it from the screenshot it does not appear to be the plugin?

Here is the code of authenticating... https://github.com/microsoftgraph/msgraph-sample-office-addin/blob/4658f0259656f68fd959ffa8df3685f96ad1c62c/graph-tutorial/src/addin/taskpane.html#L13

**Comment by Wladefant** [comment]
Just to be sure i am not uploading the plugin manifest because there isnt such an option anymore I am just starting the server with yarn start

**Comment by jasonjoh** [comment]
> Yes that was the newest version and I tried the updated version with the updated packages too. Why do you say it from the screenshot it does not appear to be the plugin?

That's not the UI in the add-in. You have to upload the manifest to get this to work. The option has moved, I've updated the README.

**Comment by Wladefant** [comment]
Thank you it works now. It wasnt clear to me that the outlook plugin is for excel from the get go. I was thinking it was for outlook (now I see it in the manifest, but before it slipped my eye apparently). Do you know of any sample or other outlook plugin that use the graph api? if yes please link them here. 

What would need to be made to transform the code to be working in outlook except for changing the code in the manifest and workbook specific implementation? For example would the consent.js need to be changed in any way?

**Comment by jasonjoh** [comment]
No I'm not aware of any sample like that. You might take a look in https://github.com/officedev to see what types of samples they have from the Office side.
