### ISSUE TITLE
The identity API is not supported for this add-in. 13000

### ISSUE THREAD

**Issue by Wladefant** [microsoftgraph/msgraph-sample-office-addin#280]
I did some minor changes to the manifest and taskpane.js to make it work in outlook and after the following error message is shown: getAccessToken error: {"name":"API Not Supported","message":"The identity API is not supported for this add-in.","code":13000}

Including this error in the terminal: Verify error: {"name":"JsonWebTokenError","message":"jwt must be provided"}

Here are the changes https://github.com/microsoftgraph/msgraph-sample-office-addin/compare/main...Wladefant:msgraph-sample-office-addin:change-to-outlook-addin

**Comment by Wladefant** [comment]
The reason seems to be that the jwt is undefined and because of that of course the graph api token can not be acquired either. What could be the problem? I have done everything imaginable, to no avail.

**Comment by Wladefant** [comment]
After hardcoding the accesstoken (API token:) and graph token that I got from running the same addin in excel it works perfectly fine

**Comment by jasonjoh** [comment]
@Wladefant this isn't a good forum to get support on Outlook add-ins. I would recommend [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/255/javascript-api) as a better option.

**Comment by Wladefant** [comment]
all right, I have asked and looked much around but I am still not able to understand why `Office.auth.getAccessToken` or `OfficeRuntime.auth.getAccessToken` works on Excel but not on Outlook. And why even though my Outlook version support the Idenitity API it show the message `he identity API is not supported for this add-in.","code":13000` 

https://learn.microsoft.com/en-us/javascript/api/office/office.auth?view=common-js-preview

**Comment by jasonjoh** [comment]
Microsoft Q&A is the best place to post your questions on add-ins. If that doesn't work out you may need to contact support.
